INDEX = ["^NSEI", "^BANKNIFTY"]

NIFTY_50 = [
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS",
    "LT.NS","SBIN.NS","ITC.NS","AXISBANK.NS","HINDUNILVR.NS",
    "BHARTIARTL.NS","KOTAKBANK.NS","BAJFINANCE.NS","BAJAJFINSV.NS",
    "HCLTECH.NS","MARUTI.NS","SUNPHARMA.NS","NTPC.NS","POWERGRID.NS",
    "M&M.NS","TITAN.NS","ULTRACEMCO.NS","ASIANPAINT.NS","ONGC.NS",
    "WIPRO.NS","COALINDIA.NS","TATASTEEL.NS","JSWSTEEL.NS",
    "INDUSINDBK.NS","GRASIM.NS","ADANIENT.NS","ADANIPORTS.NS",
    "BPCL.NS","EICHERMOT.NS","HEROMOTOCO.NS","HDFCLIFE.NS",
    "BRITANNIA.NS","CIPLA.NS","DIVISLAB.NS","DRREDDY.NS",
    "NESTLEIND.NS","APOLLOHOSP.NS","BAJAJ-AUTO.NS","SBILIFE.NS",
    "TECHM.NS","UPL.NS","TATAMOTORS.NS","HINDALCO.NS","LTIM.NS"
]

COMMODITIES = ["XAUUSD", "BTCUSD"]
